/**
 * Design Tokens - Synced from Figma
 * File: nook@shadcn_ui components with variables & Tailwind classes
 * Last synced: 2026-02-07T07:15:30.060Z
 *
 * DO NOT EDIT THIS FILE MANUALLY - Use 'npm run sync-figma-tokens' to update
 */

// ==========================================
// Typography Tokens from Figma
// ==========================================

export const typography = {
  // Font Families
  fontFamily: {
    sans: 'var(--font-geist-sans)',
    mono: 'var(--font-geist-mono)',
  },

  // Text styles from Figma
  textStyles: {
  "text-xs": {
    "black": {
      "id": "93:16",
      "name": "Text-xs/Black",
      "key": "f40fe13ccb6b6d2e17ba4af2b4ae35ece9ddb5d6"
    },
    "extra-bold": {
      "id": "93:18",
      "name": "Text-xs/Extra Bold",
      "key": "5e353cabe54fe2daab45ebb907bd829dd97d14e5"
    },
    "bold": {
      "id": "93:19",
      "name": "Text-xs/Bold",
      "key": "c0e7999dc3ceb3fd2057d3279a56dccce6f09506"
    },
    "semi-bold": {
      "id": "93:20",
      "name": "Text-xs/Semi Bold",
      "key": "f1c0ba9ccd3c7cfcf605cd6a33a1d6cdc725ee98"
    },
    "medium": {
      "id": "93:21",
      "name": "Text-xs/Medium",
      "key": "428fc431f5c40bdcb844f18a2011b1325f0a1694"
    },
    "regular": {
      "id": "93:22",
      "name": "Text-xs/Regular",
      "key": "4d0116414699bca5528f9586f26469201ec00dfb"
    },
    "light": {
      "id": "93:23",
      "name": "Text-xs/Light",
      "key": "0931d5d21fe4238889e1e0bf8e2380329fb51a32"
    },
    "extra-light": {
      "id": "93:24",
      "name": "Text-xs/Extra Light",
      "key": "3332193b34f1346f3b9ce1fc72c793563e9746a8"
    },
    "thin": {
      "id": "93:25",
      "name": "Text-xs/Thin",
      "key": "91223cbd13491279c45cba7b92e9913c9bb48e72"
    }
  },
  "text-sm": {
    "black": {
      "id": "94:34",
      "name": "Text-sm/Black",
      "key": "e1f8e0f17c044003d95796b0f2c3a6f2955665c3"
    },
    "extra-bold": {
      "id": "94:35",
      "name": "Text-sm/Extra Bold",
      "key": "2cdb245a047e0089c488f134e24753483c71baf4"
    },
    "bold": {
      "id": "94:36",
      "name": "Text-sm/Bold",
      "key": "af8a3913a29cc9985f4812bd1f668f3c086f0912"
    },
    "semi-bold": {
      "id": "94:37",
      "name": "Text-sm/Semi Bold",
      "key": "a8c6f88af24d2b487d9fac389998d72d5b75065a"
    },
    "medium": {
      "id": "1:72",
      "name": "text-sm/medium",
      "key": "715dd886ea59b7366aaa7e6fb39c54ca118c5ff2"
    },
    "regular": {
      "id": "10:280",
      "name": "text-sm/regular",
      "key": "fc79fb08bee65b9035228ba096416bbfb9369f44"
    },
    "light": {
      "id": "94:40",
      "name": "Text-sm/Light",
      "key": "cd31087ba839e86e6d98891a30ea200ac37d13ce"
    },
    "extra-light": {
      "id": "94:42",
      "name": "Text-sm/Extra Light",
      "key": "504e9a99c0e799ef01f7f8377ee5e7d523c4596f"
    },
    "thin": {
      "id": "94:43",
      "name": "Text-sm/Thin",
      "key": "dbfa4ed96a99ed45fdc4e69985a9424ceb11c6f0"
    }
  },
  "text-base": {
    "black": {
      "id": "94:44",
      "name": "Text-base/Black",
      "key": "5274f16e59e42af22df744569d12d685adc4d830"
    },
    "extra-bold": {
      "id": "94:45",
      "name": "Text-base/Extra Bold",
      "key": "f4404a703baf541769e82b9a76e8c1eb19ef2570"
    },
    "bold": {
      "id": "94:46",
      "name": "Text-base/Bold",
      "key": "d4c114775b8a0a6110c6fc1b1d6319ff49c25c86"
    },
    "semi-bold": {
      "id": "94:47",
      "name": "Text-base/Semi Bold",
      "key": "9fd5bc0ed532f7874b7409ef26eba51a69a945b1"
    },
    "medium": {
      "id": "94:48",
      "name": "Text-base/Medium",
      "key": "7887c05d5a7d495c8827b5ea8cd536d5c04c34ca"
    },
    "regular": {
      "id": "94:49",
      "name": "Text-base/Regular",
      "key": "1b8351841c72bfd4c29ee8504695c5af9ac60e58"
    },
    "light": {
      "id": "94:50",
      "name": "Text-base/Light",
      "key": "2c16ed81477ea8d1a0baf8a220482d519ac04b30"
    },
    "extra-light": {
      "id": "94:51",
      "name": "Text-base/Extra Light",
      "key": "9303caba1643d35657fdad480db7e8760a61e29d"
    },
    "thin": {
      "id": "94:52",
      "name": "Text-base/Thin",
      "key": "ef8e9ef776a20fa67de18e026483d7ab92f0de37"
    }
  },
  "text-lg": {
    "black": {
      "id": "94:53",
      "name": "Text-lg/Black",
      "key": "8521ab33b66c31e4cbcc03ce859c617229bddaaa"
    },
    "extra-bold": {
      "id": "94:54",
      "name": "Text-lg/Extra Bold",
      "key": "31895f9f71da2e80eb07751f6065141c09df236d"
    },
    "bold": {
      "id": "94:55",
      "name": "Text-lg/Bold",
      "key": "bef2bf13ab59394501d4ff2d89bb14e4c04453ce"
    },
    "semi-bold": {
      "id": "94:56",
      "name": "Text-lg/Semi Bold",
      "key": "08ea1dabf82b0d447b3545d8437c27d2a0663959"
    },
    "medium": {
      "id": "94:57",
      "name": "Text-lg/Medium",
      "key": "8297d4d70d3c6eace86205bd1f371b53c8174530"
    },
    "regular": {
      "id": "94:58",
      "name": "Text-lg/Regular",
      "key": "063af30d79ef7c194b7e54b091762328abc52f18"
    },
    "light": {
      "id": "94:59",
      "name": "Text-lg/Light",
      "key": "90965b4a66f3cdbed7163be50703f38b03dde372"
    },
    "extra-light": {
      "id": "94:60",
      "name": "Text-lg/Extra Light",
      "key": "35ca46b23cb3b1a72fb7b4c9a6ad0d8ef7ed708c"
    },
    "thin": {
      "id": "94:61",
      "name": "Text-lg/Thin",
      "key": "ad59d9a95dfd2c9b065255e9692d9953b92f5a70"
    }
  },
  "text-xl": {
    "black": {
      "id": "94:62",
      "name": "Text-xl/Black",
      "key": "a3d82b33c64db3259bed3bf9ac4c9e67111b97c6"
    },
    "extra-bold": {
      "id": "94:63",
      "name": "Text-xl/Extra Bold",
      "key": "5a4bd523de4c787f1c6bd60729daaaa0607abc10"
    },
    "bold": {
      "id": "94:64",
      "name": "Text-xl/Bold",
      "key": "8461702f16a13f8b0217ed673de46aaa0da37b15"
    },
    "semi-bold": {
      "id": "94:65",
      "name": "Text-xl/Semi Bold",
      "key": "236b07c2c49db7b4e7d39b0bc824e63d4b0e47c7"
    },
    "medium": {
      "id": "94:66",
      "name": "Text-xl/Medium",
      "key": "10608eb06856067b79e03de5bd1adb78f52faf1d"
    },
    "regular": {
      "id": "94:67",
      "name": "Text-xl/Regular",
      "key": "a50889e9312bd7041e139a7b6fb2cceca39a7436"
    },
    "light": {
      "id": "94:68",
      "name": "Text-xl/Light",
      "key": "916b1f6ee31f10f16fb6171ce0779de9827154c5"
    },
    "extra-light": {
      "id": "94:69",
      "name": "Text-xl/Extra Light",
      "key": "8925e2330b777e3ae9a8ca75b8607a11d8859561"
    },
    "thin": {
      "id": "94:70",
      "name": "Text-xl/Thin",
      "key": "b62bbbeb9b34d07500b896cfb7b9f7f987e626bd"
    }
  },
  "text-2xl": {
    "black": {
      "id": "94:71",
      "name": "Text-2xl/Black",
      "key": "b59daf9d5352da1d459d1d2a346dc080f34660ac"
    },
    "extra-bold": {
      "id": "94:72",
      "name": "Text-2xl/Extra Bold",
      "key": "35fda3d45cb0a645162d6fc9afcc315b4168b8c4"
    },
    "bold": {
      "id": "94:73",
      "name": "Text-2xl/Bold",
      "key": "3f95dd52796412d0a495559639b0c05b4c4da081"
    },
    "semi-bold": {
      "id": "94:74",
      "name": "Text-2xl/Semi Bold",
      "key": "36221c1003029132a9266f5dd5b569d060fe668f"
    },
    "medium": {
      "id": "94:75",
      "name": "Text-2xl/Medium",
      "key": "83068fab5b42c5131ab92ecd47cea0290d1f098b"
    },
    "regular": {
      "id": "94:76",
      "name": "Text-2xl/Regular",
      "key": "ce850eb05d50b86d6d273a36b4fbfd2539ea3a1e"
    },
    "light": {
      "id": "94:77",
      "name": "Text-2xl/Light",
      "key": "4496b2e919190771174d50b2f1e0078b02762e9a"
    },
    "extra-light": {
      "id": "94:78",
      "name": "Text-2xl/Extra Light",
      "key": "b69a0c204baf9ce7f808f7f28916cbf4511753e0"
    },
    "thin": {
      "id": "94:79",
      "name": "Text-2xl/Thin",
      "key": "ed2ea98a8db98182d19f49a04a5a656157a51015"
    }
  },
  "text-3xl": {
    "black": {
      "id": "94:80",
      "name": "Text-3xl/Black",
      "key": "c0e8727c6151758a2ab8ce16f9d730bb0c6580cc"
    },
    "extra-bold": {
      "id": "94:81",
      "name": "Text-3xl/Extra Bold",
      "key": "6b08d2597cacc48e3dd2cf3e66bfdd260c3900a4"
    },
    "bold": {
      "id": "94:82",
      "name": "Text-3xl/Bold",
      "key": "c98c562c3af23328f7b0386e9b4b5fe7b9f2ebcd"
    },
    "semi-bold": {
      "id": "94:83",
      "name": "Text-3xl/Semi Bold",
      "key": "d6419c6d87db88ff59672ea52205da2bb510b3c0"
    },
    "medium": {
      "id": "94:84",
      "name": "Text-3xl/Medium",
      "key": "2c4cbedeacd08bf8394c61705e14a87f80b4742e"
    },
    "regular": {
      "id": "94:85",
      "name": "Text-3xl/Regular",
      "key": "00c5e53c1bc7357e9d3df57b2096802ccfded9f9"
    },
    "light": {
      "id": "94:86",
      "name": "Text-3xl/Light",
      "key": "8e25c62f142bb1bc2edb63fc9af8b28511ee8618"
    },
    "extra-light": {
      "id": "94:87",
      "name": "Text-3xl/Extra Light",
      "key": "0317c80a53e2c45678a07969e340ca2136dfddee"
    },
    "thin": {
      "id": "94:88",
      "name": "Text-3xl/Thin",
      "key": "cd562c4c776bb4343becafeab09848d13398a7e6"
    }
  },
  "text-4xl": {
    "black": {
      "id": "94:89",
      "name": "Text-4xl/Black",
      "key": "cc15e9b64c9acba88ea5f4479d5903ddfb3dc238"
    },
    "extra-bold": {
      "id": "94:90",
      "name": "Text-4xl/Extra Bold",
      "key": "8a0340958c798dfdb0ee1adb274409abbe5ac022"
    },
    "bold": {
      "id": "94:91",
      "name": "Text-4xl/Bold",
      "key": "18a2138dd14bd2839e71f3a239718ed9e05f6d64"
    },
    "semi-bold": {
      "id": "94:92",
      "name": "Text-4xl/Semi Bold",
      "key": "89f60ea00dd736b6003af625a36ae0ec23fb2995"
    },
    "medium": {
      "id": "94:93",
      "name": "Text-4xl/Medium",
      "key": "54ebb85a1be8d44d3da8af1918efcc1b7b0909ee"
    },
    "regular": {
      "id": "94:94",
      "name": "Text-4xl/Regular",
      "key": "eaf2766ecc722658e9bc5c0df7ebfff67d5a65f7"
    },
    "light": {
      "id": "94:95",
      "name": "Text-4xl/Light",
      "key": "9d664abaef6fe0d293b549cbe573405cea3956db"
    },
    "extra-light": {
      "id": "94:96",
      "name": "Text-4xl/Extra Light",
      "key": "6ff4221d160cfedc5329e5e20b1d3b6ae8fc6e04"
    },
    "thin": {
      "id": "94:97",
      "name": "Text-4xl/Thin",
      "key": "32230f6a43ee36eaafec01be8cba8d4fb1360561"
    }
  },
  "text-5xl": {
    "black": {
      "id": "94:98",
      "name": "Text-5xl/Black",
      "key": "be951d46b23f2784f56b34af37e395b34e8dd2df"
    },
    "extra-bold": {
      "id": "94:99",
      "name": "Text-5xl/Extra Bold",
      "key": "234e10728d7c9936ed40539446c11c6ebd712da5"
    },
    "bold": {
      "id": "94:100",
      "name": "Text-5xl/Bold",
      "key": "ef8b97f335133ef46110cddb8746fe602e0daa4d"
    },
    "semi-bold": {
      "id": "94:101",
      "name": "Text-5xl/Semi Bold",
      "key": "e7d66931dea06c092f8307c93075417e66222103"
    },
    "medium": {
      "id": "94:102",
      "name": "Text-5xl/Medium",
      "key": "0d6f34fc8be8cc0fe2c323e44f442ed83615ea45"
    },
    "regular": {
      "id": "94:103",
      "name": "Text-5xl/Regular",
      "key": "bf52ed8be9357eb2337cc9a2629ce147f49e4517"
    },
    "light": {
      "id": "94:104",
      "name": "Text-5xl/Light",
      "key": "e1096e772d50664045251b78f266fe61edd55273"
    },
    "extra-light": {
      "id": "94:105",
      "name": "Text-5xl/Extra Light",
      "key": "e279aae977ade0b0104cf85b23c3c0b5e96f1d91"
    },
    "thin": {
      "id": "94:106",
      "name": "Text-5xl/Thin",
      "key": "ec1f17ad2effd586e8bbf5ccace7902f5cd55614"
    }
  },
  "text-6xl": {
    "black": {
      "id": "94:107",
      "name": "Text-6xl/Black",
      "key": "f98855d4a20b7506478d8f7e433bf6b2f4f6b870"
    },
    "extra-bold": {
      "id": "94:108",
      "name": "Text-6xl/Extra Bold",
      "key": "a551113b864b89c4a1ca73132b02609f3ca26969"
    },
    "bold": {
      "id": "94:109",
      "name": "Text-6xl/Bold",
      "key": "7642c8cdbb9d5e9ecd30f38634fd004f217b9407"
    },
    "semi-bold": {
      "id": "94:110",
      "name": "Text-6xl/Semi Bold",
      "key": "31923dd24382fcb55648c98ab01bc87451810e30"
    },
    "medium": {
      "id": "94:111",
      "name": "Text-6xl/Medium",
      "key": "8a44bf47ecc0337a69e8a5f81b95691a1e097b48"
    },
    "regular": {
      "id": "94:112",
      "name": "Text-6xl/Regular",
      "key": "d746f5a26f0763a51c6c3b38730537f15897fb09"
    },
    "light": {
      "id": "94:113",
      "name": "Text-6xl/Light",
      "key": "37b7ac8efde09a0d17fee3f246bb6a49f9f1e977"
    },
    "extra-light": {
      "id": "94:114",
      "name": "Text-6xl/Extra Light",
      "key": "2756f739378a0e6f9d3a432235c7ffea40889d88"
    },
    "thin": {
      "id": "94:115",
      "name": "Text-6xl/Thin",
      "key": "ed2161236e93ae72d19807f554419b080059d115"
    }
  },
  "text-7xl": {
    "black": {
      "id": "94:116",
      "name": "Text-7xl/Black",
      "key": "74eb5defe26bbc6798a32dc314cc116b30b61db1"
    },
    "extra-bold": {
      "id": "94:117",
      "name": "Text-7xl/Extra Bold",
      "key": "a1bb9bcd059e7791e5f102dfe816f9630cf2bccb"
    },
    "bold": {
      "id": "94:118",
      "name": "Text-7xl/Bold",
      "key": "ae89be8089c1c391ebe0396b11ea239ef9fd9c70"
    },
    "semi-bold": {
      "id": "94:119",
      "name": "Text-7xl/Semi Bold",
      "key": "474ee351ad870953d8d5e0d2f71442bc8b4a76f2"
    },
    "medium": {
      "id": "94:120",
      "name": "Text-7xl/Medium",
      "key": "e59d8451c5bfb6494ea5af8cff461d38caacb1f1"
    },
    "regular": {
      "id": "94:121",
      "name": "Text-7xl/Regular",
      "key": "846fb2512cd0832623f03b7648cd095311eaf8ff"
    },
    "light": {
      "id": "94:122",
      "name": "Text-7xl/Light",
      "key": "5f6bb600f6d7b627a7e7909f5baf72f4f27896b0"
    },
    "extra-light": {
      "id": "94:123",
      "name": "Text-7xl/Extra Light",
      "key": "d909176cffa0e73ccf528d92ca069c3076e915e0"
    },
    "thin": {
      "id": "94:124",
      "name": "Text-7xl/Thin",
      "key": "66e3940b57ab1eea7f05438aa0f641ca82f3938f"
    }
  },
  "text-8xl": {
    "black": {
      "id": "94:125",
      "name": "Text-8xl/Black",
      "key": "b6fccce2cdb5eb21312a4befaaf60e6a7e82dde6"
    },
    "extra-bold": {
      "id": "94:126",
      "name": "Text-8xl/Extra Bold",
      "key": "7ae4decb3dc7969cd74676829bae0c715fe1dca8"
    },
    "bold": {
      "id": "94:127",
      "name": "Text-8xl/Bold",
      "key": "8e8f0c475488807df3cf5010a381084090ed701a"
    },
    "semi-bold": {
      "id": "94:128",
      "name": "Text-8xl/Semi Bold",
      "key": "f417fe50af0aa61f23a08d1b58cc11364e534cc0"
    },
    "medium": {
      "id": "94:129",
      "name": "Text-8xl/Medium",
      "key": "d327ba4d3333a78034814de57736164734b0dbfd"
    },
    "regular": {
      "id": "94:130",
      "name": "Text-8xl/Regular",
      "key": "8ccbdebe5f2483f38694f9ad25cd92c95c634c6d"
    },
    "light": {
      "id": "94:131",
      "name": "Text-8xl/Light",
      "key": "f180c32a377a9353786b1a2c420f90936dd15afb"
    },
    "extra-light": {
      "id": "94:132",
      "name": "Text-8xl/Extra Light",
      "key": "2e2a303be5eb5c7f1ddbd8020c2d657872085acd"
    },
    "thin": {
      "id": "94:133",
      "name": "Text-8xl/Thin",
      "key": "2040fd3e32144aa33719f9e5861fd86b1abf9330"
    }
  },
  "text-9xl": {
    "black": {
      "id": "94:134",
      "name": "Text-9xl/Black",
      "key": "b88fd37599f64cc5b2e7104720eedcb989468de8"
    },
    "extra-bold": {
      "id": "94:135",
      "name": "Text-9xl/Extra Bold",
      "key": "baf673ee2ecb3cb67045ad12f5b900af764341bf"
    },
    "bold": {
      "id": "94:136",
      "name": "Text-9xl/Bold",
      "key": "aef11b538fd990185fbab0aa1f23fd52fe52e68b"
    },
    "semi-bold": {
      "id": "94:137",
      "name": "Text-9xl/Semi Bold",
      "key": "d1c0fd41eacf2b2cd55e871fec61276d5d29e3d8"
    },
    "medium": {
      "id": "94:138",
      "name": "Text-9xl/Medium",
      "key": "34c3bbe2150b7d75e40ce9bf3236c8c60e3ba6d0"
    },
    "regular": {
      "id": "94:139",
      "name": "Text-9xl/Regular",
      "key": "2bae6b4192c2fabbfa3f5de910cd813e86ec7804"
    },
    "light": {
      "id": "94:140",
      "name": "Text-9xl/Light",
      "key": "cb5c9ca38db4c97cd7cbea86c8821a76b6a341ea"
    },
    "extra-light": {
      "id": "94:141",
      "name": "Text-9xl/Extra Light",
      "key": "449f6b56a24e88d473c7c2f0be20564a0a18b4a6"
    },
    "thin": {
      "id": "94:142",
      "name": "Text-9xl/Thin",
      "key": "0a96366fd27ba125044458dd2ec3c31fc850943e"
    }
  }
},
}

// ==========================================
// Effect Tokens from Figma
// ==========================================

export const effects = {
  // Box shadows
  shadows: {
  "shadow-sm": {
    "id": "94:188",
    "name": "Box Shadow/shadow-sm",
    "key": "f9daeb6c525cf16acabc6853abaafd6a944ece44"
  },
  "shadow-md": {
    "id": "94:203",
    "name": "Box Shadow/shadow-md",
    "key": "a70aae1aa526290f48faaa0e1f41fd25116bfb68"
  },
  "shadow-lg": {
    "id": "96:207",
    "name": "Box Shadow/shadow-lg",
    "key": "4527b0f3651224d98a90ddc99b53e31b87e6564b"
  },
  "shadow-xl": {
    "id": "96:210",
    "name": "Box Shadow/shadow-xl",
    "key": "d5f6fb2b0125796e0a8daa6e9d1ff90d3b001215"
  },
  "shadow-2xl": {
    "id": "96:212",
    "name": "Box Shadow/shadow-2xl",
    "key": "d07ff29c9a03743242c4a67967fbda22c7f06e6f"
  },
  "shadow-none": {
    "id": "96:213",
    "name": "Box Shadow/shadow-none",
    "key": "a8de4898f2133757fed66acdf60e5c0a28b32fe2"
  },
  "shadow-inner": {
    "id": "96:237",
    "name": "Box Shadow/shadow-inner",
    "key": "ca0786673f9dbb87ebc08c0fa5dee0c16917a7ad"
  },
  "shadow-xs": {
    "id": "402:712",
    "name": "Box Shadow/shadow-xs",
    "key": "55c9dd0df18d6160c5056f4d6a4c15d67c341273"
  },
  "shadow-2xs": {
    "id": "402:713",
    "name": "Box Shadow/shadow-2xs",
    "key": "04767eb992d5102657d59a2c76feee7bd9a4b3a2"
  },
  "focus-ring": {
    "id": "588:102",
    "name": "Box Shadow/Focus ring",
    "key": "5e19af84704b5445aa9c00a4ae7e947052d35fa3"
  },
  "destructive": {
    "id": "1264:805",
    "name": "Box Shadow/Destructive",
    "key": "558785ed4db9d86dbc61e6b6aef8663d02d54870"
  },
  "default": {
    "id": "3007:5",
    "name": "Shadow",
    "key": "a8ee3ab3d83d8a9c4f9776602783278bc6aa5bbc"
  }
},

  // Blur effects
  blur: {
  "blur-none": {
    "id": "96:223",
    "name": "Blur/blur-none",
    "key": "eabb35332cbf1fe10e0cd3660bffc57880b5bf15"
  },
  "blur-sm": {
    "id": "96:224",
    "name": "Blur/blur-sm",
    "key": "2e24e4c4db6134a9927b5c35919c1023155838ae"
  },
  "blur": {
    "id": "96:225",
    "name": "Blur/blur",
    "key": "e94f54f2d299b4d26d61fba52d5efd8384345177"
  },
  "blur-md": {
    "id": "96:226",
    "name": "Blur/blur-md",
    "key": "85ecf15eb5aedde42c2cd140071b7c90c6b04c3e"
  },
  "blur-lg": {
    "id": "96:227",
    "name": "Blur/blur-lg",
    "key": "597b4ccf4107dcfdf75914c553b44d52a2a3934f"
  },
  "blur-xl": {
    "id": "96:228",
    "name": "Blur/blur-xl",
    "key": "dd4d4b9729a67b532af17884ff28e4fbf88f48fa"
  },
  "blur-2xl": {
    "id": "96:229",
    "name": "Blur/blur-2xl",
    "key": "f4111fe81605f11c632e18f7fd3980c7dd2d28db"
  },
  "blur-3xl": {
    "id": "96:230",
    "name": "Blur/blur-3xl",
    "key": "b1e22f405bc2cec094cd7ebd24d10a227666fc08"
  }
},

  // Backdrop blur effects
  backdropBlur: {
  "backdrop-blur-none": {
    "id": "96:214",
    "name": "Backdrop Blur/backdrop-blur-none",
    "key": "0c4dfd3284d2296eb8e13b33648c289602520fce"
  },
  "backdrop-blur-sm": {
    "id": "96:215",
    "name": "Backdrop Blur/backdrop-blur-sm",
    "key": "d4a57ce1653907c6a97c2cf5a7ff9daa2491eda6"
  },
  "backdrop-blur": {
    "id": "96:216",
    "name": "Backdrop Blur/backdrop-blur",
    "key": "c4d1a2330a1bb9716ad52e7c093facb0ee1c7eb5"
  },
  "backdrop-blur-md": {
    "id": "96:217",
    "name": "Backdrop Blur/backdrop-blur-md",
    "key": "ffcab62269808470b3c907265b06f8d308e6cf54"
  },
  "backdrop-blur-lg": {
    "id": "96:218",
    "name": "Backdrop Blur/backdrop-blur-lg",
    "key": "4a74af45092b9e50df3bc50181ada8dc816c2bfc"
  },
  "backdrop-blur-xl": {
    "id": "96:219",
    "name": "Backdrop Blur/backdrop-blur-xl",
    "key": "487f3bcee597e44a2378f4d1498129cf6bc72fa3"
  },
  "backdrop-blur-2xl": {
    "id": "96:220",
    "name": "Backdrop Blur/backdrop-blur-2xl",
    "key": "f7f646dcacf5a88a4a266272496e9a7d63a2b2ad"
  },
  "backdrop-blur-3xl": {
    "id": "96:221",
    "name": "Backdrop Blur/backdrop-blur-3xl",
    "key": "aa9d1e559b896e8f86d505c615056481286bf6a2"
  }
},
}

// ==========================================
// Color Tokens
// ==========================================

export const colors = {
  // Primary Colors (Neutral)
  primary: {
    50: 'oklch(0.975 0 0)',
    100: 'oklch(0.95 0 0)',
    200: 'oklch(0.9 0 0)',
    300: 'oklch(0.8 0 0)',
    400: 'oklch(0.6 0 0)',
    500: 'oklch(0.4 0 0)',
    600: 'oklch(0.3 0 0)',
    700: 'oklch(0.25 0 0)',
    800: 'oklch(0.205 0 0)',
    900: 'oklch(0.145 0 0)',
    950: 'oklch(0.1 0 0)',
  },
  // Brown Scale (Primary Mode - from Figma Radix Colors)
  brown: {
    3: '#F6EEE7',    // Warm beige background
    6: '#E4CDB7',    // Light brown/tan
    10: '#A07553',   // Medium brown
    12: '#3E332E',   // Dark brown (primary)
  },
  // Orange Scale (Charts - from Figma Radix Colors)
  orange: {
    8: '#EC9455',    // Chart 1
    9: '#F76B15',    // Chart 2
    10: '#EF5F00',   // Chart 3
    11: '#CC4E00',   // Chart 4
    12: '#582D1D',   // Chart 5 (dark)
  },
  // Semantic Colors
  success: 'oklch(0.646 0.222 41.116)',
  warning: 'oklch(0.828 0.189 84.429)',
  error: 'oklch(0.577 0.245 27.325)',
  info: 'oklch(0.6 0.118 184.704)',
  // Neutral/Gray Colors
  gray: {
    50: 'oklch(0.985 0 0)',
    100: 'oklch(0.97 0 0)',
    200: 'oklch(0.922 0 0)',
    300: 'oklch(0.87 0 0)',
    400: 'oklch(0.708 0 0)',
    500: 'oklch(0.556 0 0)',
    600: 'oklch(0.4 0 0)',
    700: 'oklch(0.3 0 0)',
    800: 'oklch(0.205 0 0)',
    900: 'oklch(0.145 0 0)',
    950: 'oklch(0.05 0 0)',
  },
}

// ==========================================
// Mode-specific Color Tokens
// ==========================================

export const modeColors = {
  light: {
    background: 'oklch(1 0 0)',
    foreground: 'oklch(0.145 0 0)',
    card: 'oklch(1 0 0)',
    cardForeground: 'oklch(0.145 0 0)',
    popover: 'oklch(1 0 0)',
    popoverForeground: 'oklch(0.145 0 0)',
    primary: 'oklch(0.205 0 0)',
    primaryForeground: 'oklch(0.985 0 0)',
    secondary: 'oklch(0.97 0 0)',
    secondaryForeground: 'oklch(0.205 0 0)',
    muted: 'oklch(0.97 0 0)',
    mutedForeground: 'oklch(0.556 0 0)',
    accent: 'oklch(0.97 0 0)',
    accentForeground: 'oklch(0.205 0 0)',
    destructive: 'oklch(0.577 0.245 27.325)',
    destructiveForeground: 'oklch(0.985 0 0)',
    border: 'oklch(0.922 0 0)',
    input: 'oklch(0.922 0 0)',
    ring: 'oklch(0.708 0 0)',
  },
  dark: {
    background: 'oklch(0.145 0 0)',
    foreground: 'oklch(0.985 0 0)',
    card: 'oklch(0.205 0 0)',
    cardForeground: 'oklch(0.985 0 0)',
    popover: 'oklch(0.205 0 0)',
    popoverForeground: 'oklch(0.985 0 0)',
    primary: 'oklch(0.922 0 0)',
    primaryForeground: 'oklch(0.205 0 0)',
    secondary: 'oklch(0.269 0 0)',
    secondaryForeground: 'oklch(0.985 0 0)',
    muted: 'oklch(0.269 0 0)',
    mutedForeground: 'oklch(0.708 0 0)',
    accent: 'oklch(0.269 0 0)',
    accentForeground: 'oklch(0.985 0 0)',
    destructive: 'oklch(0.704 0.191 22.216)',
    destructiveForeground: 'oklch(0.985 0 0)',
    border: 'oklch(1 0 0 / 10%)',
    input: 'oklch(1 0 0 / 15%)',
    ring: 'oklch(0.556 0 0)',
  },
  primary: {
    background: '#F6EEE7',              // Warm beige from Figma
    foreground: '#3E332E',              // Dark brown from Figma
    card: '#F6EEE7',                    // Warm beige
    cardForeground: '#3E332E',          // Dark brown
    popover: '#FFFFFF',                 // White
    popoverForeground: '#3E332E',       // Dark brown
    primary: '#3E332E',                 // Dark brown (brown/12)
    primaryForeground: '#FAFAFA',       // Off-white (neutral/50)
    secondary: '#E4CDB7',               // Light brown (brown/6)
    secondaryForeground: '#A07553',     // Medium brown (brown/10)
    muted: '#F5F5F5',                   // Light gray (neutral/100)
    mutedForeground: '#737373',         // Medium gray (neutral/500)
    accent: '#F5F5F5',                  // Light gray
    accentForeground: '#171717',        // Dark gray (neutral/900)
    destructive: '#DC2626',             // Red (red/600)
    destructiveForeground: '#FAFAFA',   // Off-white
    border: '#E5E5E5',                  // Light gray (neutral/200)
    input: '#E5E5E5',                   // Light gray
    ring: '#737373',                    // Medium gray (neutral/500)
  },
}

// ==========================================
// Spacing Tokens
// ==========================================

export const spacing = {
  0: '0',
  1: '0.25rem',
  2: '0.5rem',
  3: '0.75rem',
  4: '1rem',
  5: '1.25rem',
  6: '1.5rem',
  8: '2rem',
  10: '2.5rem',
  12: '3rem',
  16: '4rem',
  20: '5rem',
  24: '6rem',
}

// ==========================================
// Border Radius Tokens
// ==========================================

export const borderRadius = {
  none: '0',
  sm: 'calc(var(--radius) - 4px)',
  base: 'calc(var(--radius) - 2px)',
  md: 'var(--radius)',
  lg: 'calc(var(--radius) + 4px)',
  xl: 'calc(var(--radius) + 8px)',
  '2xl': 'calc(var(--radius) + 12px)',
  '3xl': 'calc(var(--radius) + 16px)',
  full: '9999px',
}

// ==========================================
// Z-Index Tokens
// ==========================================

export const zIndex = {
  hide: -1,
  base: 0,
  dropdown: 1000,
  sticky: 1020,
  fixed: 1030,
  modal: 1040,
  popover: 1050,
  tooltip: 1060,
}

// ==========================================
// Breakpoints (Responsive)
// ==========================================

export const breakpoints = {
  xs: '0px',
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px',
}

// ==========================================
// Figma Variables Reference
// ==========================================

export const figmaVariables = {
  collection: 'shadcn/ui',
  collectionId: 'VariableCollectionId:372:453',
  modes: {
    light: {
      id: '372:1',
      name: 'Light Mode',
      description: 'Default light theme with high contrast',
    },
    dark: {
      id: '373:0',
      name: 'Dark Mode',
      description: 'Dark theme optimized for low-light environments',
    },
    primary: {
      id: '5248:0',
      name: 'Primary Mode',
      description: 'Brown/warm earth tone theme with natural colors',
    },
  },
}

// ==========================================
// Helper Functions
// ==========================================

/**
 * Get color tokens for a specific mode
 */
export function getModeColors(mode: 'light' | 'dark' | 'primary') {
  return modeColors[mode]
}

/**
 * Get all available modes
 */
export function getAllModes() {
  return Object.keys(figmaVariables.modes) as Array<'light' | 'dark' | 'primary'>
}

/**
 * Get mode info by name
 */
export function getModeInfo(mode: 'light' | 'dark' | 'primary') {
  return figmaVariables.modes[mode]
}
