#!/usr/bin/env tsx

/**
 * Figma Design Tokens Sync Script
 *
 * This script syncs design tokens from Figma to the local project.
 * It fetches styles from Figma and generates design token files.
 *
 * Usage: npm run sync-figma-tokens
 */

import fs from 'fs'
import path from 'path'

const FIGMA_FILE_KEY = 'sdA9LFFgl6VNgmrHKdIMf9'
const FIGMA_TOKEN = process.env.FIGMA_API_TOKEN || ''
const API_BASE = 'https://api.figma.com/v1'

interface FigmaStyle {
  key: string
  name: string
  styleType: 'TEXT' | 'FILL' | 'EFFECT' | 'GRID'
  description: string
}

interface FigmaTextStyle {
  fontFamily: string
  fontWeight: number
  fontSize: number
  lineHeight: { value: number; unit: string }
  letterSpacing: { value: number; unit: string }
}

/**
 * Fetch Figma file styles
 */
async function fetchFigmaStyles(): Promise<Record<string, FigmaStyle>> {
  const response = await fetch(`${API_BASE}/files/${FIGMA_FILE_KEY}`, {
    headers: {
      'X-Figma-Token': FIGMA_TOKEN,
    },
  })

  if (!response.ok) {
    throw new Error(`Figma API error: ${response.statusText}`)
  }

  const data = await response.json()
  return data.styles || {}
}

/**
 * Fetch style details by ID
 */
async function fetchStyleById(styleId: string): Promise<any> {
  const response = await fetch(`${API_BASE}/files/${FIGMA_FILE_KEY}/nodes?ids=${styleId}`, {
    headers: {
      'X-Figma-Token': FIGMA_TOKEN,
    },
  })

  if (!response.ok) {
    throw new Error(`Failed to fetch style ${styleId}: ${response.statusText}`)
  }

  const data = await response.json()
  return data.nodes?.[styleId]
}

/**
 * Parse text styles from Figma
 */
function parseTextStyles(styles: Record<string, FigmaStyle>): Record<string, any> {
  const textStyles: Record<string, any> = {}

  Object.entries(styles).forEach(([id, style]) => {
    if (style.styleType === 'TEXT') {
      const nameParts = style.name.split('/')
      const category = nameParts[0]?.trim().toLowerCase()
      const variant = nameParts[1]?.trim().toLowerCase().replace(/\s+/g, '-')

      if (!textStyles[category]) {
        textStyles[category] = {}
      }

      textStyles[category][variant] = {
        id,
        name: style.name,
        key: style.key,
      }
    }
  })

  return textStyles
}

/**
 * Parse effect styles (shadows, blur) from Figma
 */
function parseEffectStyles(styles: Record<string, FigmaStyle>): Record<string, any> {
  const effectStyles: Record<string, any> = {
    shadows: {},
    blur: {},
    backdropBlur: {},
  }

  Object.entries(styles).forEach(([id, style]) => {
    if (style.styleType === 'EFFECT') {
      const name = style.name.toLowerCase()

      if (name.includes('shadow')) {
        const variant = name.split('/')[1]?.trim().replace(/\s+/g, '-') || 'default'
        effectStyles.shadows[variant] = {
          id,
          name: style.name,
          key: style.key,
        }
      } else if (name.includes('backdrop') && name.includes('blur')) {
        const variant = name.split('/')[1]?.trim().replace(/\s+/g, '-') || 'default'
        effectStyles.backdropBlur[variant] = {
          id,
          name: style.name,
          key: style.key,
        }
      } else if (name.includes('blur')) {
        const variant = name.split('/')[1]?.trim().replace(/\s+/g, '-') || 'default'
        effectStyles.blur[variant] = {
          id,
          name: style.name,
          key: style.key,
        }
      }
    }
  })

  return effectStyles
}

/**
 * Generate design tokens file
 */
function generateDesignTokensFile(
  textStyles: Record<string, any>,
  effectStyles: Record<string, any>
): string {
  return `/**
 * Design Tokens - Synced from Figma
 * File: nook@shadcn_ui components with variables & Tailwind classes
 * Last synced: ${new Date().toISOString()}
 *
 * DO NOT EDIT THIS FILE MANUALLY - Use 'npm run sync-figma-tokens' to update
 */

// ==========================================
// Typography Tokens from Figma
// ==========================================

export const typography = {
  // Font Families
  fontFamily: {
    sans: 'var(--font-geist-sans)',
    mono: 'var(--font-geist-mono)',
  },

  // Text styles from Figma
  textStyles: ${JSON.stringify(textStyles, null, 2)},
}

// ==========================================
// Effect Tokens from Figma
// ==========================================

export const effects = {
  // Box shadows
  shadows: ${JSON.stringify(effectStyles.shadows, null, 2)},

  // Blur effects
  blur: ${JSON.stringify(effectStyles.blur, null, 2)},

  // Backdrop blur effects
  backdropBlur: ${JSON.stringify(effectStyles.backdropBlur, null, 2)},
}

// ==========================================
// Color Tokens
// ==========================================

export const colors = {
  // Primary Colors
  primary: {
    50: 'oklch(0.975 0 0)',
    100: 'oklch(0.95 0 0)',
    200: 'oklch(0.9 0 0)',
    300: 'oklch(0.8 0 0)',
    400: 'oklch(0.6 0 0)',
    500: 'oklch(0.4 0 0)',
    600: 'oklch(0.3 0 0)',
    700: 'oklch(0.25 0 0)',
    800: 'oklch(0.205 0 0)',
    900: 'oklch(0.145 0 0)',
    950: 'oklch(0.1 0 0)',
  },
  // Semantic Colors
  success: 'oklch(0.646 0.222 41.116)',
  warning: 'oklch(0.828 0.189 84.429)',
  error: 'oklch(0.577 0.245 27.325)',
  info: 'oklch(0.6 0.118 184.704)',
  // Neutral/Gray Colors
  gray: {
    50: 'oklch(0.985 0 0)',
    100: 'oklch(0.97 0 0)',
    200: 'oklch(0.922 0 0)',
    300: 'oklch(0.87 0 0)',
    400: 'oklch(0.708 0 0)',
    500: 'oklch(0.556 0 0)',
    600: 'oklch(0.4 0 0)',
    700: 'oklch(0.3 0 0)',
    800: 'oklch(0.205 0 0)',
    900: 'oklch(0.145 0 0)',
    950: 'oklch(0.05 0 0)',
  },
}

// ==========================================
// Spacing Tokens
// ==========================================

export const spacing = {
  0: '0',
  1: '0.25rem',
  2: '0.5rem',
  3: '0.75rem',
  4: '1rem',
  5: '1.25rem',
  6: '1.5rem',
  8: '2rem',
  10: '2.5rem',
  12: '3rem',
  16: '4rem',
  20: '5rem',
  24: '6rem',
}

// ==========================================
// Border Radius Tokens
// ==========================================

export const borderRadius = {
  none: '0',
  sm: 'calc(var(--radius) - 4px)',
  base: 'calc(var(--radius) - 2px)',
  md: 'var(--radius)',
  lg: 'calc(var(--radius) + 4px)',
  xl: 'calc(var(--radius) + 8px)',
  '2xl': 'calc(var(--radius) + 12px)',
  '3xl': 'calc(var(--radius) + 16px)',
  full: '9999px',
}

// ==========================================
// Z-Index Tokens
// ==========================================

export const zIndex = {
  hide: -1,
  base: 0,
  dropdown: 1000,
  sticky: 1020,
  fixed: 1030,
  modal: 1040,
  popover: 1050,
  tooltip: 1060,
}

// ==========================================
// Breakpoints (Responsive)
// ==========================================

export const breakpoints = {
  xs: '0px',
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px',
}

// ==========================================
// Figma Variables Reference
// ==========================================

export const figmaVariables = {
  collection: 'shadcn/ui',
  collectionId: 'VariableCollectionId:372:453',
  modes: {
    light: '372:1',
    dark: '373:0',
    primary: '5248:0',
  },
}
`
}

/**
 * Main sync function
 */
async function syncFigmaTokens() {
  console.log('🎨 Syncing Figma design tokens...')
  console.log(`📁 File: ${FIGMA_FILE_KEY}`)

  try {
    // Fetch styles from Figma
    console.log('📥 Fetching styles from Figma...')
    const styles = await fetchFigmaStyles()
    console.log(`✅ Found ${Object.keys(styles).length} styles`)

    // Parse different style types
    console.log('🔄 Parsing text styles...')
    const textStyles = parseTextStyles(styles)

    console.log('🔄 Parsing effect styles...')
    const effectStyles = parseEffectStyles(styles)

    // Generate design tokens file
    console.log('📝 Generating design tokens file...')
    const content = generateDesignTokensFile(textStyles, effectStyles)

    // Write to file
    const outputPath = path.join(process.cwd(), 'lib', 'design-tokens.ts')
    fs.writeFileSync(outputPath, content, 'utf-8')

    console.log(`✅ Design tokens synced successfully!`)
    console.log(`📄 Output: ${outputPath}`)

    // Summary
    console.log('\n📊 Summary:')
    console.log(`  - Text styles: ${Object.keys(textStyles).length} categories`)
    console.log(`  - Shadow styles: ${Object.keys(effectStyles.shadows).length}`)
    console.log(`  - Blur styles: ${Object.keys(effectStyles.blur).length}`)
    console.log(`  - Backdrop blur styles: ${Object.keys(effectStyles.backdropBlur).length}`)

  } catch (error) {
    console.error('❌ Error syncing Figma tokens:', error)
    process.exit(1)
  }
}

// Run the sync
syncFigmaTokens()
